Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "win2016_tas50"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-api_box-default-windows-2016-c5507de1-1193-4cc2-91e0-20c3bd9c13ad"
    p.customize ["modifyvm", :id, "--audio", "none"]
    p.customize ["modifyvm", :id, "--cpus", "2"]
    p.customize ["modifyvm", :id, "--memory", "4096"]
  end
end
